version: '3'
services:

  safenetwork-root-ipv4:
    build:
      context: ./
      dockerfile: ./src/root-ipv4/Dockerfile

'''
  safenetwork-root-ipv6:
    build:
      context: ./
      dockerfile: ./src/root-ipv6/Dockerfile
  
  safenetwork-node-ipv4:
    build:
      context: ./
      dockerfile: ./src/node-ipv4/Dockerfile
  
  safenetwork-node-ipv6:
    build:
      context: ./
      dockerfile: ./src/node-ipv6/Dockerfile
'''   
